"""Pydantic model for chat response, used in the chat API."""

from pydantic import BaseModel, Field


class ChatResponse(BaseModel):
    """Pydantic model for chat response."""

    response: str = Field(description="The response generated by the model.")
    chunk: str = Field(
        description="The chunk from the knowledge base that was used to generate the response."
    )
    document: str = Field(description="The document the chunk was extracted from.")
    page: int = Field(description="The page number the chunk was extracted from.")
