logger:
  loguru_level: "INFO"

llm:
  provider: "Ollama" # Options: "Ollama", "Gemini"

chunking:
  method: "FixedSize" # Options: "FixedSize"
  size: 400
  overlap: 60

vector_db:
  provider: "Chroma" # Options: "Chroma"

run:
  workflow: "Default" # Options: "Default"
